version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(go):"
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(npm):"
    labels:
      - dependencies
      - frontend

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(docker):"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(actions):"
    labels:
      - dependencies
      - ci
