/**
 * Typed API surface generated from `docs/openapi.yaml`.
 *
 * `schema.ts` is auto-generated by openapi-typescript (`pnpm gen:api`) — do not
 * edit it by hand. This barrel re-exports the generated types plus small
 * ergonomic helpers so feature services can be typed directly against the spec.
 * When the spec changes, regenerating turns any drift into a compile error.
 */
export type { paths, components, operations } from './schema';

import type { components } from './schema';

/** Convenience alias for the spec's reusable component schemas. */
export type Schemas = components['schemas'];

/**
 * The standard success envelope returned by the API wraps payloads as
 * `{ success, data, timestamp }`. The Go side marks `data` with `omitempty`, so
 * the generated types model it as optional. `unwrap` asserts its presence and
 * narrows the type for callers, which expect the inner payload.
 */
export function unwrap<T>(envelope: { data?: T }): T {
  if (envelope.data === undefined) {
    throw new Error('API response envelope is missing its "data" field');
  }
  return envelope.data;
}
