import { z } from 'zod';

/**
 * Frontend validation schemas for audit-critical inputs.
 *
 * Hand-authored validators live here (not in shared/api/schema.ts, which is
 * generated by openapi-typescript and would overwrite manual edits on
 * `gen:api`).
 *
 * Schemas:
 *   - passwordSchema: shared by auth setup, user-management, and the
 *     configuration auth fields. Length unified to >= 8 chars (was 6 in
 *     AuthSettings, 8 in UserModal).
 *   - dotenvSchema: validates a multi-line .env payload before PUT
 *     /env/dotenv. Rejects empty keys, lines starting with `=`, and
 *     malformed separators.
 *   - settingsRawSchema: validates raw settings.js content before POST.
 *     Uses `new Function(content)` to syntax-check without executing.
 */

// Password: >= 8 chars, trims input. Reused across auth forms to enforce
// a single rule (fixes the 6-vs-8 char inconsistency).
export const passwordSchema = z
  .string()
  .trim()
  .min(8, 'Password must be at least 8 characters');

// Single .env line: optional leading whitespace, key=value, trailing
// optional whitespace. Key regex allows alphanumerics, underscores and
// dots (Dokploy-style). Empty lines and `#`-prefixed comments are
// accepted as-is by the multi-line schema, not here.
const DOTENV_LINE_RE = /^(\s*)([A-Za-z_][A-Za-z0-9_.]*)\s*=\s*(.*?)\s*$/;

// dotenvSchema accepts a multi-line string. Each non-empty, non-comment
// line must match KEY=VALUE. Empty lines and comments pass through.
export const dotenvSchema = z.string().superRefine((content, ctx) => {
  const lines = content.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const trimmed = raw.trim();
    if (trimmed === '' || trimmed.startsWith('#')) {
      continue;
    }
    if (!DOTENV_LINE_RE.test(raw)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Line ${i + 1} is malformed: expected KEY=VALUE`,
        path: ['line', i],
      });
      return;
    }
    if (trimmed.startsWith('=')) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Line ${i + 1}: missing key`,
        path: ['line', i],
      });
      return;
    }
  }
});

// settingsRawSchema accepts a string that should be valid JavaScript. We
// parse it with `new Function(...)` which throws SyntaxError on malformed
// input but never executes the body.
export const settingsRawSchema = z.string().refine(
  (content) => {
    try {
      // Wrap in a function so any top-level `return` is allowed (matches
      // how the Node-RED editor loads settings.js). `new Function` only
      // compiles; it does not run the code.
      new Function(content);
      return true;
    } catch {
      return false;
    }
  },
  { message: 'settings.js is not valid JavaScript' }
);

// Helper: safe parser that returns the issues map instead of throwing.
export function formatZodIssues(error: z.ZodError): Record<string, string> {
  const out: Record<string, string> = {};
  for (const issue of error.issues) {
    const key = issue.path.join('.') || '_root';
    if (!out[key]) {
      out[key] = issue.message;
    }
  }
  return out;
}
