package service

import (
	"strings"
	"testing"

	"nrcc/internal/model"
)

// TestRenderSettingsJS_Defaults tests rendering with default configuration
func TestRenderSettingsJS_Defaults(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	output := RenderSettingsJS(cfg)

	// Check header
	if !strings.Contains(output, "// Auto-generated by Node-RED Control Center") {
		t.Error("Missing auto-generated header")
	}

	// Check module.exports
	if !strings.Contains(output, "module.exports = {") {
		t.Error("Missing module.exports opening")
	}

	// Check default server values
	if !strings.Contains(output, `uiPort: 1880`) {
		t.Error("Missing uiPort: 1880")
	}

	if !strings.Contains(output, `uiHost: "0.0.0.0"`) {
		t.Error("Missing uiHost")
	}

	// Check credentialSecret renders as false when empty
	if !strings.Contains(output, `credentialSecret: false`) {
		t.Error("credentialSecret should render as false when empty string")
	}

	// Check flowFile
	if !strings.Contains(output, `flowFile: "flows.json"`) {
		t.Error("Missing flowFile default")
	}

	// Check Node Reconnect values
	if !strings.Contains(output, `mqttReconnectTime: 5000`) {
		t.Error("Missing mqttReconnectTime")
	}

	// Check closing
	if !strings.Contains(output, "};") {
		t.Error("Missing module.exports closing")
	}

	// Check valid JavaScript structure
	if !strings.Contains(output, "paletteCategories:") {
		t.Error("Missing paletteCategories")
	}
}

// TestRenderSettingsJS_HTTPS tests HTTPS configuration
func TestRenderSettingsJS_HTTPS(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.HTTPS.Enabled = true
	cfg.HTTPS.KeyFile = "/etc/ssl/key.pem"
	cfg.HTTPS.CertFile = "/etc/ssl/cert.pem"
	cfg.HTTPS.CAFile = "/etc/ssl/ca.pem"

	output := RenderSettingsJS(cfg)

	// Check fs require
	if !strings.Contains(output, "const fs = require('fs');") {
		t.Error("Missing fs require for HTTPS")
	}

	// Check key readFileSync
	if !strings.Contains(output, `key: fs.readFileSync("/etc/ssl/key.pem")`) {
		t.Error("Missing key readFileSync")
	}

	// Check cert readFileSync
	if !strings.Contains(output, `cert: fs.readFileSync("/etc/ssl/cert.pem")`) {
		t.Error("Missing cert readFileSync")
	}

	// Check CA readFileSync
	if !strings.Contains(output, `ca: fs.readFileSync("/etc/ssl/ca.pem")`) {
		t.Error("Missing ca readFileSync")
	}

	// Verify fs is only required once
	fsCount := strings.Count(output, "const fs = require('fs');")
	if fsCount != 1 {
		t.Errorf("fs require should appear exactly once, got %d", fsCount)
	}
}

// TestRenderSettingsJS_HTTPS_NoCA tests HTTPS without CA file
func TestRenderSettingsJS_HTTPS_NoCA(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.HTTPS.Enabled = true
	cfg.HTTPS.KeyFile = "/etc/ssl/key.pem"
	cfg.HTTPS.CertFile = "/etc/ssl/cert.pem"
	cfg.HTTPS.CAFile = ""

	output := RenderSettingsJS(cfg)

	// Check that CA is NOT present
	if strings.Contains(output, "ca: fs.readFileSync") {
		t.Error("CA should not be rendered when empty")
	}

	// But key and cert should still be there
	if !strings.Contains(output, `key: fs.readFileSync("/etc/ssl/key.pem")`) {
		t.Error("Missing key readFileSync")
	}
}

// TestRenderSettingsJS_AdminAuth tests adminAuth configuration
func TestRenderSettingsJS_AdminAuth(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Security.AdminAuth = &model.AdminAuthConfig{
		Type: "credentials",
		Users: []model.AdminAuthUser{
			{
				Username:    "admin",
				Password:    "$2a$10$hash",
				Permissions: "*",
			},
		},
		Default: &model.AdminAuthDefault{
			Permissions: "read",
		},
	}

	output := RenderSettingsJS(cfg)

	// Check adminAuth block
	if !strings.Contains(output, `adminAuth: {`) {
		t.Error("Missing adminAuth block")
	}

	// Check type
	if !strings.Contains(output, `type: "credentials"`) {
		t.Error("Missing adminAuth type")
	}

	// Check users
	if !strings.Contains(output, `username: "admin"`) {
		t.Error("Missing username")
	}

	// Check default
	if !strings.Contains(output, `default: {`) {
		t.Error("Missing adminAuth default")
	}

	if !strings.Contains(output, `permissions: "read"`) {
		t.Error("Missing adminAuth default permissions")
	}
}

// TestRenderSettingsJS_AdminAuth_NoDefault tests adminAuth without default
func TestRenderSettingsJS_AdminAuth_NoDefault(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Security.AdminAuth = &model.AdminAuthConfig{
		Type: "credentials",
		Users: []model.AdminAuthUser{
			{
				Username:    "admin",
				Password:    "$2a$10$hash",
				Permissions: "*",
			},
		},
		Default: nil,
	}

	output := RenderSettingsJS(cfg)

	// Check adminAuth block still present
	if !strings.Contains(output, `adminAuth: {`) {
		t.Error("Missing adminAuth block")
	}

	// Check default is NOT present
	lines := strings.Split(output, "\n")
	inAdminAuth := false
	defaultFound := false
	for _, line := range lines {
		if strings.Contains(line, "adminAuth: {") {
			inAdminAuth = true
		}
		if inAdminAuth && strings.Contains(line, "default: {") {
			defaultFound = true
		}
		if inAdminAuth && strings.Contains(line, "},") && !strings.Contains(line, "adminAuth") {
			inAdminAuth = false
		}
	}

	if defaultFound {
		t.Error("adminAuth default should not be rendered when nil")
	}
}

// TestRenderSettingsJS_HTTPNodeRoot_False tests httpNodeRoot special case
func TestRenderSettingsJS_HTTPNodeRoot_False(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Server.HTTPNodeRoot = "false"

	output := RenderSettingsJS(cfg)

	// Check that "false" string renders as JavaScript boolean false
	if !strings.Contains(output, `httpNodeRoot: false,`) {
		t.Error("httpNodeRoot: 'false' should render as JavaScript false boolean, not string")
	}

	// Make sure it doesn't render as "false" string
	if strings.Contains(output, `httpNodeRoot: "false"`) {
		t.Error("httpNodeRoot should not render as quoted string when value is 'false'")
	}
}

// TestRenderSettingsJS_HTTPNodeRoot_String tests httpNodeRoot with normal string
func TestRenderSettingsJS_HTTPNodeRoot_String(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Server.HTTPNodeRoot = "/api"

	output := RenderSettingsJS(cfg)

	// Check that normal string renders as quoted string
	if !strings.Contains(output, `httpNodeRoot: "/api"`) {
		t.Error("httpNodeRoot should render as quoted string when not 'false'")
	}
}

// TestRenderSettingsJS_NoEditorTheme tests that editorTheme block is absent when not needed
func TestRenderSettingsJS_NoEditorTheme(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	// Ensure all editorTheme fields are default/empty
	cfg.EditorTheme = model.EditorThemeConfig{
		Theme:        "",
		Page:         nil,
		Header:       nil,
		DeployButton: nil,
		Tours:        true,
		UserMenu:     true,
		Projects:     model.EditorProjectsConfig{Enabled: false},
		CodeEditor:   nil,
	}

	output := RenderSettingsJS(cfg)

	// Check that editorTheme block is NOT present
	if strings.Contains(output, `editorTheme: {`) {
		t.Error("editorTheme block should not be rendered when all fields are default")
	}
}

// TestRenderSettingsJS_EditorTheme_WithTheme tests editorTheme with theme set
func TestRenderSettingsJS_EditorTheme_WithTheme(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.EditorTheme.Theme = "dark"

	output := RenderSettingsJS(cfg)

	// Check that editorTheme block IS present
	if !strings.Contains(output, `editorTheme: {`) {
		t.Error("Missing editorTheme block when theme is set")
	}

	if !strings.Contains(output, `theme: "dark"`) {
		t.Error("Missing theme property")
	}
}

// TestRenderSettingsJS_EditorTheme_WithPage tests editorTheme with page config
func TestRenderSettingsJS_EditorTheme_WithPage(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.EditorTheme.Page = &model.EditorPageConfig{
		Title:   "My Node-RED",
		Favicon: "/favicon.ico",
		CSS:     "/custom.css",
	}

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `editorTheme: {`) {
		t.Error("Missing editorTheme block when page is set")
	}

	if !strings.Contains(output, `page: {`) {
		t.Error("Missing page block")
	}

	if !strings.Contains(output, `title: "My Node-RED"`) {
		t.Error("Missing page title")
	}
}

// TestRenderSettingsJS_EditorTheme_WithHeader tests editorTheme with header config
func TestRenderSettingsJS_EditorTheme_WithHeader(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.EditorTheme.Header = &model.EditorHeaderConfig{
		Title: "Node-RED Control Center",
		Image: "/logo.png",
		URL:   "http://example.com",
	}

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `header: {`) {
		t.Error("Missing header block")
	}

	if !strings.Contains(output, `title: "Node-RED Control Center"`) {
		t.Error("Missing header title")
	}
}

// TestRenderSettingsJS_EditorTheme_WithDeployButton tests editorTheme with deployButton config
func TestRenderSettingsJS_EditorTheme_WithDeployButton(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.EditorTheme.DeployButton = &model.EditorDeployButtonConfig{
		Type:  "confirm",
		Label: "Deploy Now",
	}

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `deployButton: {`) {
		t.Error("Missing deployButton block")
	}

	if !strings.Contains(output, `type: "confirm"`) {
		t.Error("Missing deployButton type")
	}

	if !strings.Contains(output, `label: "Deploy Now"`) {
		t.Error("Missing deployButton label")
	}
}

// TestRenderSettingsJS_EditorTheme_WithCodeEditor tests editorTheme with codeEditor config
func TestRenderSettingsJS_EditorTheme_WithCodeEditor(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.EditorTheme.CodeEditor = &model.EditorCodeConfig{
		Lib: "monaco",
		Options: map[string]string{
			"fontSize": "14",
			"theme":    "vs-dark",
		},
	}

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `codeEditor: {`) {
		t.Error("Missing codeEditor block")
	}

	if !strings.Contains(output, `lib: "monaco"`) {
		t.Error("Missing codeEditor lib")
	}

	if !strings.Contains(output, `options: {`) {
		t.Error("Missing options block in codeEditor")
	}
}

// TestRenderSettingsJS_ContextStorage tests context storage configuration
func TestRenderSettingsJS_ContextStorage(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.ContextStorage.Stores = map[string]model.ContextStoreEntry{
		"default": {
			Module: "memory",
			Config: map[string]any{},
		},
		"file": {
			Module: "localfilesystem",
			Config: map[string]any{
				"dir": "/data/context",
			},
		},
	}

	output := RenderSettingsJS(cfg)

	// Check contextStorage block
	if !strings.Contains(output, `contextStorage: {`) {
		t.Error("Missing contextStorage block")
	}

	// Check default store
	if !strings.Contains(output, `default: "default"`) {
		t.Error("Missing contextStorage default")
	}

	// Check stores object
	if !strings.Contains(output, `stores: {`) {
		t.Error("Missing stores object")
	}

	// Check memory store
	if !strings.Contains(output, `module: "memory"`) {
		t.Error("Missing memory module")
	}

	// Check file store
	if !strings.Contains(output, `module: "localfilesystem"`) {
		t.Error("Missing localfilesystem module")
	}

	// Check config in file store
	if !strings.Contains(output, `dir: "/data/context"`) {
		t.Error("Missing file store config")
	}
}

// TestRenderSettingsJS_CredentialSecret tests credentialSecret rendering
func TestRenderSettingsJS_CredentialSecret(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Security.CredentialSecret = "my-secret-key"

	output := RenderSettingsJS(cfg)

	// Check that non-empty secret renders as quoted string
	if !strings.Contains(output, `credentialSecret: "my-secret-key"`) {
		t.Error("credentialSecret should render as quoted string when non-empty")
	}

	// Make sure it doesn't render as false
	if strings.Contains(output, `credentialSecret: false`) {
		t.Error("credentialSecret should not render as false when non-empty")
	}
}

// TestRenderSettingsJS_ExternalModules tests externalModules configuration
func TestRenderSettingsJS_ExternalModules(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Runtime.ExternalModules = &model.ExternalModulesConfig{
		AutoInstall:      true,
		AutoInstallRetry: 60,
		Palette: model.ExternalModulesPaletteConfig{
			AllowInstall: true,
			AllowUpload:  false,
			AllowList:    []string{"node-red-contrib-foo"},
			DenyList:     []string{"node-red-contrib-bar"},
		},
		Modules: model.ExternalModulesModuleConfig{
			AllowInstall: true,
			AllowList:    []string{"@org/package"},
			DenyList:     []string{"bad-package"},
		},
	}

	output := RenderSettingsJS(cfg)

	// Check externalModules block
	if !strings.Contains(output, `externalModules: {`) {
		t.Error("Missing externalModules block")
	}

	// Check autoInstall
	if !strings.Contains(output, `autoInstall: true`) {
		t.Error("Missing autoInstall")
	}

	// Check autoInstallRetry
	if !strings.Contains(output, `autoInstallRetry: 60`) {
		t.Error("Missing autoInstallRetry")
	}

	// Check palette section
	if !strings.Contains(output, `palette: {`) {
		t.Error("Missing palette section in externalModules")
	}

	// Check palette allowList
	if !strings.Contains(output, `allowList: ["node-red-contrib-foo"]`) {
		t.Error("Missing palette allowList")
	}

	// Check modules section
	if !strings.Contains(output, `modules: {`) {
		t.Error("Missing modules section in externalModules")
	}

	// Check modules allowList
	if !strings.Contains(output, `allowList: ["@org/package"]`) {
		t.Error("Missing modules allowList")
	}
}

// TestRenderSettingsJS_HTTPStatic tests httpStatic only included when non-empty
func TestRenderSettingsJS_HTTPStatic(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Server.HTTPStatic = "/static"

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `httpStatic: "/static"`) {
		t.Error("Missing httpStatic when non-empty")
	}

	// Test empty httpStatic is omitted
	cfg.Server.HTTPStatic = ""
	output = RenderSettingsJS(cfg)

	if strings.Contains(output, "httpStatic:") {
		t.Error("httpStatic should be omitted when empty")
	}
}

// TestRenderSettingsJS_DisableEditor tests disableEditor only included when true
func TestRenderSettingsJS_DisableEditor(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Server.DisableEditor = true

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `disableEditor: true`) {
		t.Error("Missing disableEditor when true")
	}

	// Test false disableEditor is omitted
	cfg.Server.DisableEditor = false
	output = RenderSettingsJS(cfg)

	if strings.Contains(output, "disableEditor:") {
		t.Error("disableEditor should be omitted when false")
	}
}

// TestRenderSettingsJS_UserDir tests userDir only included when non-empty
func TestRenderSettingsJS_UserDir(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Flows.UserDir = "/home/node-red"

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `userDir: "/home/node-red"`) {
		t.Error("Missing userDir when non-empty")
	}

	// Test empty userDir is omitted
	cfg.Flows.UserDir = ""
	output = RenderSettingsJS(cfg)

	if strings.Contains(output, "userDir:") {
		t.Error("userDir should be omitted when empty")
	}
}

// TestRenderSettingsJS_NodesDir tests nodesDir only included when non-empty
func TestRenderSettingsJS_NodesDir(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Flows.NodesDir = "/custom/nodes"

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `nodesDir: "/custom/nodes"`) {
		t.Error("Missing nodesDir when non-empty")
	}

	// Test empty nodesDir is omitted
	cfg.Flows.NodesDir = ""
	output = RenderSettingsJS(cfg)

	if strings.Contains(output, "nodesDir:") {
		t.Error("nodesDir should be omitted when empty")
	}
}

// TestRenderSettingsJS_HTTPNodeAuth tests httpNodeAuth configuration
func TestRenderSettingsJS_HTTPNodeAuth(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Security.HTTPNodeAuth = &model.HTTPNodeAuthConfig{
		User: "node-user",
		Pass: "$2a$10$hash",
	}

	output := RenderSettingsJS(cfg)

	// Check httpNodeAuth block
	if !strings.Contains(output, `httpNodeAuth: {`) {
		t.Error("Missing httpNodeAuth block")
	}

	if !strings.Contains(output, `user: "node-user"`) {
		t.Error("Missing httpNodeAuth user")
	}

	if !strings.Contains(output, `pass: "$2a$10$hash"`) {
		t.Error("Missing httpNodeAuth pass")
	}
}

// TestRenderSettingsJS_SafeMode tests safeMode only included when true
func TestRenderSettingsJS_SafeMode(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Runtime.SafeMode = true

	output := RenderSettingsJS(cfg)

	if !strings.Contains(output, `safeMode: true`) {
		t.Error("Missing safeMode when true")
	}

	// Test false safeMode is omitted
	cfg.Runtime.SafeMode = false
	output = RenderSettingsJS(cfg)

	if strings.Contains(output, "safeMode:") {
		t.Error("safeMode should be omitted when false")
	}
}

// TestRenderSettingsJS_StringEscaping tests that strings with special characters are properly escaped
func TestRenderSettingsJS_StringEscaping(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Server.HTTPStatic = `/path/with/"quotes"`
	cfg.Flows.FlowFile = `flows"with"quotes.json`

	output := RenderSettingsJS(cfg)

	// Check that quotes are escaped
	if !strings.Contains(output, `httpStatic: "/path/with/\"quotes\""`) {
		t.Error("Quotes in httpStatic should be escaped")
	}

	if !strings.Contains(output, `flowFile: "flows\"with\"quotes.json"`) {
		t.Error("Quotes in flowFile should be escaped")
	}
}

// TestRenderSettingsJS_ValidJavaScript checks basic JavaScript validity
func TestRenderSettingsJS_ValidJavaScript(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	output := RenderSettingsJS(cfg)

	// Check for balanced braces
	openBraces := strings.Count(output, "{")
	closeBraces := strings.Count(output, "}")
	if openBraces != closeBraces {
		t.Errorf("Unbalanced braces: %d open, %d close", openBraces, closeBraces)
	}

	// Check for balanced brackets
	openBrackets := strings.Count(output, "[")
	closeBrackets := strings.Count(output, "]")
	if openBrackets != closeBrackets {
		t.Errorf("Unbalanced brackets: %d open, %d close", openBrackets, closeBrackets)
	}

	// Check for module.exports
	if !strings.Contains(output, "module.exports = {") {
		t.Error("Missing module.exports declaration")
	}

	// Check for closing semicolon
	if !strings.Contains(output, "};") {
		t.Error("Missing closing semicolon")
	}
}

// TestRenderSettingsJS_ComplexConfig tests a complex configuration with multiple features
func TestRenderSettingsJS_ComplexConfig(t *testing.T) {
	cfg := model.DefaultFullAppConfig()
	cfg.Server.UIPort = 3000
	cfg.Server.HTTPStatic = "/public"
	cfg.Security.CredentialSecret = "secret123"
	cfg.Security.AdminAuth = &model.AdminAuthConfig{
		Type: "credentials",
		Users: []model.AdminAuthUser{
			{
				Username:    "admin",
				Password:    "hash1",
				Permissions: "*",
			},
			{
				Username:    "viewer",
				Password:    "hash2",
				Permissions: "read",
			},
		},
		Default: &model.AdminAuthDefault{
			Permissions: "read",
		},
	}
	cfg.HTTPS.Enabled = true
	cfg.HTTPS.KeyFile = "/certs/key.pem"
	cfg.HTTPS.CertFile = "/certs/cert.pem"
	cfg.Runtime.ExternalModules = &model.ExternalModulesConfig{
		AutoInstall:      false,
		AutoInstallRetry: 30,
		Palette: model.ExternalModulesPaletteConfig{
			AllowInstall: true,
			AllowUpload:  false,
			AllowList:    []string{},
			DenyList:     []string{},
		},
		Modules: model.ExternalModulesModuleConfig{
			AllowInstall: true,
			AllowList:    []string{},
			DenyList:     []string{},
		},
	}

	output := RenderSettingsJS(cfg)

	// Verify all components are present
	if !strings.Contains(output, "const fs = require('fs');") {
		t.Error("Missing fs require")
	}

	if !strings.Contains(output, `uiPort: 3000`) {
		t.Error("Missing custom uiPort")
	}

	if !strings.Contains(output, `credentialSecret: "secret123"`) {
		t.Error("Missing credentialSecret")
	}

	if !strings.Contains(output, `username: "admin"`) {
		t.Error("Missing admin user")
	}

	if !strings.Contains(output, `username: "viewer"`) {
		t.Error("Missing viewer user")
	}

	if !strings.Contains(output, `key: fs.readFileSync("/certs/key.pem")`) {
		t.Error("Missing https key")
	}

	if !strings.Contains(output, `externalModules: {`) {
		t.Error("Missing externalModules")
	}

	// Validate structure
	openBraces := strings.Count(output, "{")
	closeBraces := strings.Count(output, "}")
	if openBraces != closeBraces {
		t.Errorf("Unbalanced braces in complex config: %d open, %d close", openBraces, closeBraces)
	}
}
