package service

import (
	"fmt"
	"strings"

	"nrcc/internal/model"
)

// RenderSettingsJS generates a valid Node-RED settings.js file from a FullAppConfig.
// The output is in CommonJS module.exports format, ready to be written to a file.
func RenderSettingsJS(cfg model.FullAppConfig) string {
	b := &strings.Builder{}

	// Write header
	writeHeader(b)

	// If HTTPS is enabled, include fs require
	if cfg.HTTPS.Enabled {
		b.WriteString("const fs = require('fs');\n\n")
	}

	// Start module.exports
	b.WriteString("module.exports = {\n")

	// Server section
	writeServerSection(b, cfg.Server)

	// Security section
	writeSecuritySection(b, cfg.Security)

	// Flows section
	writeFlowsSection(b, cfg.Flows)

	// Context Storage section
	writeContextStorageSection(b, cfg.ContextStorage)

	// Logging section
	writeLoggingSection(b, cfg.Logging)

	// Runtime section
	writeRuntimeSection(b, cfg.Runtime)

	// HTTPS section (if enabled)
	if cfg.HTTPS.Enabled {
		writeHTTPSSection(b, cfg.HTTPS)
	}

	// Node Reconnect section (always present)
	writeNodeReconnectSection(b, cfg.NodeReconnect)

	// Editor Theme section (only if relevant fields are set)
	if shouldEmitEditorTheme(cfg.EditorTheme) {
		writeEditorThemeSection(b, cfg.EditorTheme)
	}

	// Palette section
	writePaletteSection(b, cfg.Palette)

	// Close module.exports
	b.WriteString("};\n")

	return b.String()
}

// writeHeader writes the auto-generated file header comment
func writeHeader(b *strings.Builder) {
	b.WriteString("// Node-RED settings.js\n")
	b.WriteString("// Auto-generated by Node-RED Control Center\n")
	b.WriteString("// Do not edit manually — use the NRCC Settings UI\n\n")
}

// writeString renders a key: "value", pair
func writeString(b *strings.Builder, indent, key, value string) {
	b.WriteString(indent)
	b.WriteString(key)
	b.WriteString(": ")
	b.WriteString(fmt.Sprintf("%q", value))
	b.WriteString(",\n")
}

// writeBool renders a key: true/false, pair
func writeBool(b *strings.Builder, indent, key string, value bool) {
	b.WriteString(indent)
	b.WriteString(key)
	b.WriteString(": ")
	if value {
		b.WriteString("true")
	} else {
		b.WriteString("false")
	}
	b.WriteString(",\n")
}

// writeInt renders a key: number, pair
func writeInt(b *strings.Builder, indent, key string, value int) {
	b.WriteString(indent)
	b.WriteString(key)
	b.WriteString(": ")
	b.WriteString(fmt.Sprintf("%d", value))
	b.WriteString(",\n")
}

// writeInt64 renders a key: number, pair for int64 values
func writeInt64(b *strings.Builder, indent, key string, value int64) {
	b.WriteString(indent)
	b.WriteString(key)
	b.WriteString(": ")
	b.WriteString(fmt.Sprintf("%d", value))
	b.WriteString(",\n")
}

// writeStringArray renders a key: ["item1", "item2"], pair
func writeStringArray(b *strings.Builder, indent, key string, values []string) {
	b.WriteString(indent)
	b.WriteString(key)
	b.WriteString(": [")
	for i, v := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%q", v))
	}
	b.WriteString("],\n")
}

// writeServerSection renders the Server configuration
func writeServerSection(b *strings.Builder, cfg model.ServerConfig) {
	b.WriteString("    // Server\n")
	writeInt(b, "    ", "uiPort", cfg.UIPort)
	writeString(b, "    ", "uiHost", cfg.UIHost)
	writeString(b, "    ", "httpAdminRoot", cfg.HTTPAdminRoot)

	// httpNodeRoot: if "false" string, render as JavaScript false; otherwise as string
	if cfg.HTTPNodeRoot == "false" {
		writeBool(b, "    ", "httpNodeRoot", false)
	} else {
		writeString(b, "    ", "httpNodeRoot", cfg.HTTPNodeRoot)
	}

	// httpStatic: only if non-empty
	if cfg.HTTPStatic != "" {
		writeString(b, "    ", "httpStatic", cfg.HTTPStatic)
	}

	// disableEditor: only if true
	if cfg.DisableEditor {
		writeBool(b, "    ", "disableEditor", cfg.DisableEditor)
	}

	b.WriteString("\n")
}

// writeSecuritySection renders the Security configuration
func writeSecuritySection(b *strings.Builder, cfg model.SecurityConfig) {
	b.WriteString("    // Security\n")

	// credentialSecret: empty string renders as false
	if cfg.CredentialSecret == "" {
		writeBool(b, "    ", "credentialSecret", false)
	} else {
		writeString(b, "    ", "credentialSecret", cfg.CredentialSecret)
	}

	writeInt64(b, "    ", "sessionExpiryTime", cfg.SessionExpiryTime)

	// adminAuth: only if non-nil
	if cfg.AdminAuth != nil {
		writeAdminAuthConfig(b, cfg.AdminAuth)
	}

	// httpNodeAuth: only if non-nil
	if cfg.HTTPNodeAuth != nil {
		writeHTTPNodeAuthConfig(b, cfg.HTTPNodeAuth)
	}

	b.WriteString("\n")
}

// writeAdminAuthConfig renders the adminAuth nested object
func writeAdminAuthConfig(b *strings.Builder, cfg *model.AdminAuthConfig) {
	b.WriteString("    adminAuth: {\n")
	writeString(b, "        ", "type", cfg.Type)

	// Write users array
	b.WriteString("        users: [\n")
	for i, user := range cfg.Users {
		b.WriteString("            {\n")
		writeString(b, "                ", "username", user.Username)
		writeString(b, "                ", "password", user.Password)
		writeString(b, "                ", "permissions", user.Permissions)
		b.WriteString("            }")
		if i < len(cfg.Users)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("        ],\n")

	// default: only if non-nil
	if cfg.Default != nil {
		b.WriteString("        default: {\n")
		writeString(b, "            ", "permissions", cfg.Default.Permissions)
		b.WriteString("        },\n")
	}

	b.WriteString("    },\n")
}

// writeHTTPNodeAuthConfig renders the httpNodeAuth nested object
func writeHTTPNodeAuthConfig(b *strings.Builder, cfg *model.HTTPNodeAuthConfig) {
	b.WriteString("    httpNodeAuth: {\n")
	writeString(b, "        ", "user", cfg.User)
	writeString(b, "        ", "pass", cfg.Pass)
	b.WriteString("    },\n")
}

// writeFlowsSection renders the Flows configuration
func writeFlowsSection(b *strings.Builder, cfg model.FlowsConfig) {
	b.WriteString("    // Flows\n")
	writeString(b, "    ", "flowFile", cfg.FlowFile)
	writeBool(b, "    ", "flowFilePretty", cfg.FlowFilePretty)

	// userDir: only if non-empty
	if cfg.UserDir != "" {
		writeString(b, "    ", "userDir", cfg.UserDir)
	}

	// nodesDir: only if non-empty
	if cfg.NodesDir != "" {
		writeString(b, "    ", "nodesDir", cfg.NodesDir)
	}

	b.WriteString("\n")
}

// writeContextStorageSection renders the Context Storage configuration
func writeContextStorageSection(b *strings.Builder, cfg model.ContextStorageConfig) {
	b.WriteString("    // Context Storage\n")
	b.WriteString("    contextStorage: {\n")
	writeString(b, "        ", "default", cfg.Default)

	// Build stores object
	b.WriteString("        stores: {\n")
	storeKeys := make([]string, 0, len(cfg.Stores))
	for k := range cfg.Stores {
		storeKeys = append(storeKeys, k)
	}
	// Sort for consistent output (optional but recommended)
	// For now, we'll iterate in map order (non-deterministic but acceptable)

	storeList := make([]string, 0, len(cfg.Stores))
	for k := range cfg.Stores {
		storeList = append(storeList, k)
	}

	for i, storeName := range storeList {
		store := cfg.Stores[storeName]
		b.WriteString("            ")
		b.WriteString(storeName)
		b.WriteString(": {\n")
		writeString(b, "                ", "module", store.Module)

		// config: only if non-empty
		if len(store.Config) > 0 {
			b.WriteString("                config: {\n")
			for k, v := range store.Config {
				// Handle different value types
				switch val := v.(type) {
				case string:
					writeString(b, "                    ", k, val)
				case float64:
					b.WriteString("                    ")
					b.WriteString(k)
					b.WriteString(": ")
					b.WriteString(fmt.Sprintf("%v", int(val)))
					b.WriteString(",\n")
				case bool:
					b.WriteString("                    ")
					b.WriteString(k)
					b.WriteString(": ")
					if val {
						b.WriteString("true")
					} else {
						b.WriteString("false")
					}
					b.WriteString(",\n")
				default:
					writeString(b, "                    ", k, fmt.Sprintf("%v", val))
				}
			}
			b.WriteString("                },\n")
		}

		b.WriteString("            }")
		if i < len(storeList)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}

	b.WriteString("        },\n")
	b.WriteString("    },\n\n")
}

// writeLoggingSection renders the Logging configuration
func writeLoggingSection(b *strings.Builder, cfg model.LoggingConfig) {
	b.WriteString("    // Logging\n")
	b.WriteString("    logging: {\n")
	b.WriteString("        console: {\n")
	writeString(b, "            ", "level", cfg.Console.Level)
	writeBool(b, "            ", "metrics", cfg.Console.Metrics)
	writeBool(b, "            ", "audit", cfg.Console.Audit)
	b.WriteString("        },\n")
	b.WriteString("    },\n\n")
}

// writeRuntimeSection renders the Runtime configuration
func writeRuntimeSection(b *strings.Builder, cfg model.RuntimeConfig) {
	b.WriteString("    // Runtime\n")
	writeBool(b, "    ", "functionExternalModules", cfg.FunctionExternalModules)
	writeInt(b, "    ", "functionTimeout", cfg.FunctionTimeout)
	writeInt(b, "    ", "debugMaxLength", cfg.DebugMaxLength)
	writeBool(b, "    ", "diagnosticsEnabled", cfg.DiagnosticsEnabled)

	// safeMode: only if true
	if cfg.SafeMode {
		writeBool(b, "    ", "safeMode", cfg.SafeMode)
	}

	writeInt(b, "    ", "nodeMessageBufferMaxLength", cfg.NodeMessageBufferMaxLength)

	// externalModules: only if non-nil
	if cfg.ExternalModules != nil {
		writeExternalModulesConfig(b, cfg.ExternalModules)
	}

	b.WriteString("\n")
}

// writeExternalModulesConfig renders the externalModules nested object
func writeExternalModulesConfig(b *strings.Builder, cfg *model.ExternalModulesConfig) {
	b.WriteString("    externalModules: {\n")
	writeBool(b, "        ", "autoInstall", cfg.AutoInstall)
	writeInt(b, "        ", "autoInstallRetry", cfg.AutoInstallRetry)

	// palette
	b.WriteString("        palette: {\n")
	writeBool(b, "            ", "allowInstall", cfg.Palette.AllowInstall)
	writeBool(b, "            ", "allowUpload", cfg.Palette.AllowUpload)
	writeStringArray(b, "            ", "allowList", cfg.Palette.AllowList)
	writeStringArray(b, "            ", "denyList", cfg.Palette.DenyList)
	b.WriteString("        },\n")

	// modules
	b.WriteString("        modules: {\n")
	writeBool(b, "            ", "allowInstall", cfg.Modules.AllowInstall)
	writeStringArray(b, "            ", "allowList", cfg.Modules.AllowList)
	writeStringArray(b, "            ", "denyList", cfg.Modules.DenyList)
	b.WriteString("        },\n")

	b.WriteString("    },\n")
}

// writeHTTPSSection renders the HTTPS configuration
func writeHTTPSSection(b *strings.Builder, cfg model.HTTPSConfig) {
	b.WriteString("    // HTTPS\n")
	b.WriteString("    https: {\n")
	b.WriteString("        key: fs.readFileSync(")
	b.WriteString(fmt.Sprintf("%q", cfg.KeyFile))
	b.WriteString("),\n")
	b.WriteString("        cert: fs.readFileSync(")
	b.WriteString(fmt.Sprintf("%q", cfg.CertFile))
	b.WriteString("),\n")

	// ca: only if non-empty
	if cfg.CAFile != "" {
		b.WriteString("        ca: fs.readFileSync(")
		b.WriteString(fmt.Sprintf("%q", cfg.CAFile))
		b.WriteString("),\n")
	}

	b.WriteString("    },\n\n")
}

// writeNodeReconnectSection renders the Node Reconnect configuration (always present)
func writeNodeReconnectSection(b *strings.Builder, cfg model.NodeReconnectConfig) {
	b.WriteString("    // Node Reconnect\n")
	writeInt(b, "    ", "mqttReconnectTime", cfg.MQTTReconnectTime)
	writeInt(b, "    ", "serialReconnectTime", cfg.SerialReconnectTime)
	writeInt(b, "    ", "socketReconnectTime", cfg.SocketReconnectTime)
	writeInt(b, "    ", "socketTimeout", cfg.SocketTimeout)

	b.WriteString("\n")
}

// shouldEmitEditorTheme determines if editorTheme block should be emitted
func shouldEmitEditorTheme(cfg model.EditorThemeConfig) bool {
	if cfg.Theme != "" {
		return true
	}
	if cfg.Page != nil {
		return true
	}
	if cfg.Header != nil {
		return true
	}
	if cfg.DeployButton != nil {
		return true
	}
	if cfg.CodeEditor != nil {
		return true
	}
	if !cfg.Tours {
		return true // explicitly false
	}
	if !cfg.UserMenu {
		return true // explicitly false
	}
	if cfg.Projects.Enabled {
		return true // explicitly true
	}
	return false
}

// writeEditorThemeSection renders the Editor Theme configuration
func writeEditorThemeSection(b *strings.Builder, cfg model.EditorThemeConfig) {
	b.WriteString("    // Editor Theme\n")
	b.WriteString("    editorTheme: {\n")

	// theme: only if non-empty
	if cfg.Theme != "" {
		writeString(b, "        ", "theme", cfg.Theme)
	}

	// tours, userMenu (always emit if block exists)
	writeBool(b, "        ", "tours", cfg.Tours)
	writeBool(b, "        ", "userMenu", cfg.UserMenu)

	// projects
	b.WriteString("        projects: {\n")
	writeBool(b, "            ", "enabled", cfg.Projects.Enabled)
	b.WriteString("        },\n")

	// page: only if non-nil
	if cfg.Page != nil {
		b.WriteString("        page: {\n")
		writeString(b, "            ", "title", cfg.Page.Title)
		writeString(b, "            ", "favicon", cfg.Page.Favicon)
		writeString(b, "            ", "css", cfg.Page.CSS)
		b.WriteString("        },\n")
	}

	// header: only if non-nil
	if cfg.Header != nil {
		b.WriteString("        header: {\n")
		writeString(b, "            ", "title", cfg.Header.Title)
		writeString(b, "            ", "image", cfg.Header.Image)
		writeString(b, "            ", "url", cfg.Header.URL)
		b.WriteString("        },\n")
	}

	// deployButton: only if non-nil
	if cfg.DeployButton != nil {
		b.WriteString("        deployButton: {\n")
		writeString(b, "            ", "type", cfg.DeployButton.Type)
		writeString(b, "            ", "label", cfg.DeployButton.Label)
		b.WriteString("        },\n")
	}

	// codeEditor: only if non-nil
	if cfg.CodeEditor != nil {
		b.WriteString("        codeEditor: {\n")
		writeString(b, "            ", "lib", cfg.CodeEditor.Lib)
		b.WriteString("            options: {\n")
		for k, v := range cfg.CodeEditor.Options {
			writeString(b, "                ", k, v)
		}
		b.WriteString("            },\n")
		b.WriteString("        },\n")
	}

	b.WriteString("    },\n\n")
}

// writePaletteSection renders the Palette configuration
func writePaletteSection(b *strings.Builder, cfg model.PaletteConfig) {
	b.WriteString("    // Palette\n")
	writeStringArray(b, "    ", "paletteCategories", cfg.Categories)
}
